### ISSUE TITLE
Add ordering for SchoolFinder Component

### ISSUE THREAD

**Issue by urbrob** [urbrob/BrickSchool#15]
We should add section "Ordered_by" which user can order their schools. 
- Name
- Time travel
- Distance travel
- and other similar to filters

**Comment by Graleszczur** [comment]
Done by hakun12 using frontend side sorting.
![image](https://user-images.githubusercontent.com/33428795/65829576-39e16780-e2a7-11e9-83e1-fca5ba9c554d.png)
