### ISSUE TITLE
Create HomePage 

### ISSUE THREAD

**Issue by urbrob** [urbrob/BrickSchool#8]
- Ignore links, every can be blank.
- Make It stylish but don't waste on it too much time
- In the middle should be button "Find perfect school" with redirect to SearchView (diff task)
- Make empty navbar component (we will do it later)
- Check VirtualHouse website for inspiration.

**Comment by Graleszczur** [comment]
Home page ready with all intended components.

**Comment by Graleszczur** [comment]
Layout screen for desktop and mobile.
![image](https://user-images.githubusercontent.com/33428795/65829491-8e381780-e2a6-11e9-88bf-ad3af08306a4.png)
![image](https://user-images.githubusercontent.com/33428795/65829519-c6d7f100-e2a6-11e9-8a1e-02db93484681.png)
