### ISSUE TITLE
Create SchoolFinder Component

### ISSUE THREAD

**Issue by urbrob** [urbrob/BrickSchool#9]
At this view we will have list of schools and they can be filtered by:
- Name
- Distance from the point(less than)
- Time travel from the point(less than)
- "Perspektywy" badge
- Technical school or normal high-school
- ... and some more but that in the future

Component with school at list should be as simple as possible. Just name

**Comment by Graleszczur** [comment]
Component working with extended list of filters. Added to layout.
![image](https://user-images.githubusercontent.com/33428795/65829472-50d38a00-e2a6-11e9-8112-6e12dee72bc9.png)
